version: '3'

services:
  postgres:
    image: mdillon/postgis
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
volumes:
  postgres: